gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/base/precision/current_precision.o   ../source/base/precision/current_precision.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/base/IO/inquire_funcs.o   ../source/base/IO/inquire_funcs.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/base/IO/IO_check.o   ../source/base/IO/IO_check.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/base/IO/IO_tools.o   ../source/base/IO/IO_tools.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/base/string/string.o   ../source/base/string/string.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o ../source/base/string/string_aux.o   ../source/base/string/string_aux.f90   
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o generated_code/array.o  generated_code/array.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o generated_code/sparse.o  generated_code/sparse.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o generated_code/coordinates.o  generated_code/coordinates.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o generated_code/grid.o  generated_code/grid.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o generated_code/grid_field.o  generated_code/grid_field.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o generated_code/block.o  generated_code/block.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin" -c -o generated_code/mesh.o  generated_code/mesh.f90  
gfortran -fopenmp -g -cpp -fimplicit-none -Wall -Wextra -Wall -Wextra -pedantic -fbacktrace -fcheck=all -Wuninitialized -J"bin"  -o output C:\Users\Charlie\Documents\GitHub\goofPy\MOONS/generated_code/main_dummy.f90 ../source/base/precision/current_precision.o   ../source/base/IO/inquire_funcs.o   ../source/base/IO/IO_check.o   ../source/base/IO/IO_tools.o   ../source/base/string/string.o   ../source/base/string/string_aux.o   generated_code/array.o  generated_code/sparse.o  generated_code/coordinates.o  generated_code/grid.o  generated_code/grid_field.o  generated_code/block.o  generated_code/mesh.o  
 output.exe